### PR TITLE
Change Expires to Cache-Control

### PR DESCRIPTION
**Pull request by dpegasusm**
Modified for #189

### CODE REVIEW

**Comment by guillaumemolter** [comment]
+1

**Comment by A5hleyRich** [comment]
Thanks for the PR. Both headers will included in the next version of WP Offload S3.

**Comment by dpegasusm** [comment]
The cache-control max-age directive takes priority over Expires so having both would be be semi redundant:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html

**Comment by A5hleyRich** [comment]
Correct, but there's no harm in having it there for older browsers that don't support CacheControl.

**Comment by guillaumemolter** [comment]
@A5hleyRich when will that be implemented? I don't see it in the 2 last releases?

**Comment by A5hleyRich** [comment]
It will be available in the next release, but we don't have an ETA yet.

**Pull request closed without merging**
