### PR TITLE
fixed preview in image editor

### PR DESCRIPTION
**Pull request by noreabu**
added another allowed action and modified query to use REQUEST instead of POST

This solved my issue here: https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/issues/317

### CODE REVIEW

**Comment by A5hleyRich** [comment]
Thanks for the PR @noreabu. We'll check it out and get it merged into a future release.

**Comment by A5hleyRich** [comment]
Hey @noreabu. We're having a hard time replicating this issue using the steps provided. Are you still able to replicate the issue?

**Comment by noreabu** [comment]
Yes, it is still reproducable. Sorry for the delay.

If i upload a new image and then click on edit image there is no image visible without this fix.

**Comment by aaemnnosttv** [comment]
Hi @noreabu, image preview with the wp image editor was fixed in the latest release ([v1.2](https://github.com/deliciousbrains/wp-amazon-s3-and-cloudfront/releases/tag/1.2)).

If you still believe there to be a bug, please open a new issue for us to investigate.

**Pull request closed without merging**
